-- Avatar files are only exposed through short-lived signed URLs generated by
-- the backend. No storage.objects SELECT policy is needed for this design.
update storage.buckets
set public = false
where id = 'avatars';
